# Generated by Django 5.0.3 on 2024-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
