# Generated by Django 5.0.3 on 2024-04-04 20:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_order_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=50)),
                ("last_name", models.CharField(blank=True, default="", max_length=50)),
                ("phone", models.CharField(blank=True, default="", max_length=10)),
                ("email", models.EmailField(blank=True, default="", max_length=100)),
                ("address1", models.CharField(blank=True, default="", max_length=200)),
                ("address2", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, default="", max_length=50)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                ("zip", models.CharField(blank=True, default="", max_length=10)),
                ("country", models.CharField(blank=True, default="", max_length=50)),
                ("date", models.DateField(default=datetime.datetime.today)),
                (
                    "image",
                    models.ImageField(
                        default="uploads/profile/default.png",
                        upload_to="uploads/profile/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_profile",
            },
        ),
    ]
