# Generated by Django 5.0.3 on 2024-04-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="old_cart",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterModelTable(
            name="profile",
            table=None,
        ),
    ]
